"""initial app and marts schema

Revision ID: b190df9a91d8
Revises: 
Create Date: 2026-06-07 01:18:21.994021
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b190df9a91d8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_email'), ['email'], unique=True)

    op.create_table('mart_country',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('cur', sa.String(length=4), nullable=False),
    sa.Column('cur_code', sa.String(length=3), nullable=False),
    sa.Column('nat_factor', sa.Float(), nullable=False),
    sa.Column('ppp_rate', sa.Float(), nullable=False),
    sa.Column('transparency', sa.Float(), nullable=False),
    sa.Column('c1', sa.String(length=9), nullable=False),
    sa.Column('c2', sa.String(length=9), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('mart_family',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mart_market_pulse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mart_market_pulse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mart_market_pulse_country_code'), ['country_code'], unique=False)

    op.create_table('mart_meta',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('mart_role',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('family_id', sa.String(length=40), nullable=False),
    sa.Column('family_name', sa.String(length=80), nullable=False),
    sa.Column('family_hue', sa.Integer(), nullable=False),
    sa.Column('blurb', sa.String(length=600), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mart_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mart_role_family_id'), ['family_id'], unique=False)

    op.create_table('mart_role_country',
    sa.Column('role_id', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('interest', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('score_demand', sa.Float(), nullable=False),
    sa.Column('score_pay', sa.Float(), nullable=False),
    sa.Column('score_opp', sa.Float(), nullable=False),
    sa.Column('score_rank', sa.Integer(), nullable=False),
    sa.Column('score_pctile', sa.Integer(), nullable=False),
    sa.Column('sample', sa.Integer(), nullable=False),
    sa.Column('conf', sa.String(length=4), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('freshness', sa.String(length=40), nullable=False),
    sa.Column('transparency', sa.Float(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.Column('demand_series', sa.JSON(), nullable=False),
    sa.Column('forecast', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', 'country_code')
    )
    op.create_table('mart_role_ladder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=120), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('mult', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mart_role_ladder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mart_role_ladder_role_id'), ['role_id'], unique=False)

    op.create_table('mart_role_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=1), nullable=False),
    sa.Column('dura', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(length=10), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mart_role_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mart_role_skill_role_id'), ['role_id'], unique=False)

    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('family_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'type', 'ref_id', name='uq_fav')
    )
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_account_id'), ['account_id'], unique=False)

    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_account_id'))

    op.drop_table('resume')
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_account_id'))

    op.drop_table('favourite')
    with op.batch_alter_table('mart_role_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mart_role_skill_role_id'))

    op.drop_table('mart_role_skill')
    with op.batch_alter_table('mart_role_ladder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mart_role_ladder_role_id'))

    op.drop_table('mart_role_ladder')
    op.drop_table('mart_role_country')
    with op.batch_alter_table('mart_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mart_role_family_id'))

    op.drop_table('mart_role')
    op.drop_table('mart_meta')
    with op.batch_alter_table('mart_market_pulse', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mart_market_pulse_country_code'))

    op.drop_table('mart_market_pulse')
    op.drop_table('mart_family')
    op.drop_table('mart_country')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_email'))

    op.drop_table('account')
    # ### end Alembic commands ###
